<?php

namespace AppBundle\Repository;

/**
 * CallbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallbackRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
