<?php

namespace AppBundle\Repository;

/**
 * MaintenanceRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaintenanceRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
