<?php

namespace AppBundle\Repository;

/**
 * PartsRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartsRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
