<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityNotFoundException;

/**
 * RequestStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestStatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTitle(string $title)
    {
        $query = $this->createQueryBuilder('request_status')
            ->where("request_status.title = :title")
            ->setParameter('title', $title)
            ->getQuery();

        return $query->setMaxResults(1)->getOneOrNullResult();
    }
}
